addEventHandler( "onClientResourceStart",resourceRoot,function ( startedRes )
    resetColorFilter()
    resetSunColor()
    resetSkyGradient()
    resetSunSize()
    -- start skygfx
    initBuildingSimplePSPipeline()
    initPostFx()
    noZTest() 
end)